update from subversion

diff --git a/tlpkg/bin/tl-update-images b/tlpkg/bin/tl-update-images
--- a/tlpkg/bin/tl-update-images
+++ b/tlpkg/bin/tl-update-images
@@ -1,8 +1,8 @@
 #!/bin/sh
-# $Id: tl-update-images 27122 2012-07-23 22:05:17Z karl $
+# $Id: tl-update-images 30663 2013-05-24 00:17:12Z karl $
 # Create the .iso image(s) for TeX Live.
 # 
-# Copyright 2007, 2008, 2009, 2010, 2011, 2012 Karl Berry.
+# Copyright 2007-2013 Karl Berry.
 # Copyright 2003, 2004, 2005 Sebastian Rahtz.
 #
 # This file is licensed under the GNU General Public License version 2
@@ -12,7 +12,7 @@
 # Historical notes at the end of the script.
 
 NAME=texlive
-V=2012
+V=2013
 D=`date +%Y%m%d`
 target=/home/ftp/texlive/Images/test
 
@@ -81,13 +81,13 @@ MAKEINST ()
   mkdir $imgdir
   
   # files and a few dirs from master.
-  cp -p $master/.mkisofsrc $imgdir              # mkisofs control
-  cp -p $master/* $imgdir 2>/dev/null || true   # intentionally skip dirs
-  cp -pr $master/readme* $master/source $imgdir # do these few dirs
+  cp -p $master/.mkisofsrc $imgdir || exit 1    # mkisofs control
+  cp -p $master/* $imgdir 2>/dev/null           # intentionally skip dirs
+  cp -pr $master/readme* $master/source $imgdir # but do these few dirs
   
   # included preformatted doc in new dir for the DVD.
   mkdir $imgdir/texlive-doc
-  (cd $master/texmf/doc/texlive && tar cf - \
+  (cd $master/texmf-dist/doc/texlive && tar cf - \
      index.html */*.html */*.pdf */*.png \
    | (cd $imgdir/texlive-doc && tar xf -))
   
@@ -98,14 +98,27 @@ MAKEINST ()
   fi
   cp -pr install-tl *.bat tlpkg archive $imgdir
   
+  # remove some platforms to save space on the dvd.
+  # do this here so that they can be kept in the tree,
+  # and thus installed normally over the net.
+  prune="mips-irix alpha-linux powerpc-linux i386-kfreebsd amd64-kfreebsd \
+         mipsel-linux armel-linux armhf-linux"
+  echo "-- pruning platforms $prune..."
+  mkdir $imgdir/tlpkg/bin
+  cp $mydir/tl-prune-platforms $imgdir/tlpkg/bin
+  $imgdir/tlpkg/bin/tl-prune-platforms $prune >/tmp/imgprune
+
+  # some files we don't want in the image after all.
+  rm -rf $imgdir/doc.html $imgdir/tlpkg/texlive.tlpdb.xz $imgdir/tlpkg/bin
+
+  # the actual iso build.
   cd $imgdir || exit 1
-  # cleanups of files we didn't want after all.
-  rm doc.html tlpkg/texlive.tlpdb.xz
   cmd="$mkisofs $common_mkisofs_options -o $iso ."
   echo "-- `date` with: $cmd"
   $cmd
   if test $? -ne 0; then
-    echo "$0: $mkisofs failed, goodbye." >&2
+    echo "$0: $mkisofs failed (status $?), goodbye." >&2
+    exit $?
   fi
   chmod a+rw $iso
   
@@ -136,9 +149,9 @@ MAKEINST ()
 # Make the tar files: the sources, the texmf trees, the binaries, the
 # minor "extra" files.  Each should unpack into its directory name.  We
 # use the GNU tar --transform option to avoid copying the whole
-# hierarchy to temp directory.  This auxiliary function takes that
-# directory name as its first argument, and the files to archive as the
-# rest.
+# hierarchy to a temp directory.  This auxiliary function takes that
+# temp directory name as its first argument, and the files to archive as
+# the rest.
 # 
 do_tar ()
 {
@@ -172,8 +185,20 @@ do_tar ()
 
 MAKETAR ()
 {
+  echo
+  echo "-- `date` Writing tars to $target"
+
   # remove old tarballs and checksums.
   rm -f $target/$NAME-*.tar.*
+
+  # make tar files based on the tree we are running out of.
+  cd $master || exit 1
+  do_tar $NAME-$D-extra \
+         LICENSE* README* autorun.inf *.html install* re* tl-* \
+         tlpkg/TeXLive tlpkg/translations tlpkg/tlpostcode
+
+  cd $master || exit 1
+  do_tar $NAME-$D-texmf texmf*
 
   if $tar_bin_only || $tar_all; then
     cd $master/bin || exit 1
@@ -182,18 +207,15 @@ MAKETAR ()
   fi
   
   if $tar_source_only || $tar_all; then
-    cd $master/../Build/source || exit
+    cd $master/../Build/source || exit 1
     do_tar $NAME-$D-source *
     $tar_source_only && return
   fi
-
+  
+  # one more unusual case: the development sources, which we record in
+  # the 00texlive.image (fake) package; see its .tlpsrc.
   cd $master || exit 1
-  do_tar $NAME-$D-extra \
-         LICENSE* README* autorun.inf *.html install* re* tl-* \
-         tlpkg/TeXLive tlpkg/translations tlpkg/tlpostcode
-
-  cd $master || exit 1
-  do_tar $NAME-$D-texmf texmf*
+  do_tar $NAME-$D-devsource `$mydir/tlpfiles 00texlive.image`
 }
 
 
diff --git a/tlpkg/bin/tl-update-tlnet b/tlpkg/bin/tl-update-tlnet
--- a/tlpkg/bin/tl-update-tlnet
+++ b/tlpkg/bin/tl-update-tlnet
@@ -1,15 +1,15 @@
 #!/bin/sh -e
-# Copyright 2008, 2009, 2010, 2011, 2012 Norbert Preining
+# Copyright 2008-2013 Norbert Preining
 # This file is licensed under the GNU General Public License version 2
 # or any later version.
 # 
 # Update a TeX Live tlnet area, with testing.
 
-vc_id='$Id: tl-update-tlnet 26418 2012-05-15 23:26:55Z karl $'
+vc_id='$Id: tl-update-tlnet 30954 2013-06-26 22:45:47Z karl $'
 unset CDPATH
 unset LS_COLORS
 
-yyyy=2012
+yyyy=2013
 
 chicken=false
 critical=
@@ -115,17 +115,23 @@ option_fmt 1
 option_letter 0
 option_src 1
 option_path 0
+option_adjustrepo 1
 " >texlive.profile
 
-echo "$0: Running test install (log: `pwd`/install.log)..."
-perl install-tl -location $tltry -profile texlive.profile >install.log 2>&1\
-|| true # install-tl can fail, but we test the output, so don't abort.
+# silence warnings we do not need to see.
+TEXLIVE_INSTALL_ENV_NOCHECK=1; export TEXLIVE_INSTALL_ENV_NOCHECK
+
+tlnet_install_log=`pwd`/install.log
+echo "$0: Running test install (log: $tlnet_install_log)..."
+perl install-tl -location $tltry -profile texlive.profile \
+  >$tlnet_install_log 2>&1 \
+  || true # install-tl can fail, but we test the output, so don't abort.
 
 # the following long grep command should filter away all *normal*
 # installation messages.
 # if there are any other messages they will end up on stdout and 
 # thus be noticed.
-unexpected_output=`cat install.log \
+unexpected_output=`cat $tlnet_install_log \
   | sed '/The following environment variables/,/^ ------/d' \
   | grep -Ev '^ ------' \
   | grep -Ev '^Automated TeX Live installation using profile' \
@@ -156,6 +162,7 @@ unexpected_output=`cat install.log \
   | grep -Ev '^ Add ' \
   | grep -Ev '^ Most importantly, add ' \
   | grep -Ev '^ to your PATH for current and future sessions' \
+  | grep -Ev ' \(if not dynamically found\)' \
   | grep -Ev '^ Welcome to TeX Live' \
   | grep -Ev 'install-tl: done' \
   | grep -Ev '^Logfile: ' \
@@ -170,6 +177,7 @@ unexpected_output=`cat install.log \
 failure=false
 if test -n "$unexpected_output"; then
   failure=true
+  echo >&2
   echo "$0: Test installation failed." >&2
   echo "$0: Here is the unexpected output:" >&2
   echo "$unexpected_output" >&2
@@ -178,9 +186,9 @@ fi
 # more consistency checks.
 if test $failure = false; then
   for cmd in \
-      "$tltryinst/$yyyy/bin/*/tlmgr --repository $tltry update --list" \
-      "$Master/tlpkg/bin/check-tlnet-consistency --location=$tltry" \
-      "$Master/tlpkg/bin/tl-compare-tlpdbs $critical $tltry/tlpkg/texlive.tlpdb" \
+   "$tltryinst/$yyyy/bin/*/tlmgr --repository $tltry update --list" \
+   "$Master/tlpkg/bin/check-tlnet-consistency --location=$tltry" \
+   "$Master/tlpkg/bin/tl-compare-tlpdbs $critical $tltry/tlpkg/texlive.tlpdb" \
   ; do
     cmdname=`echo "$cmd" | awk '{print $1}'`
     basecmd=`basename $cmdname`
@@ -196,11 +204,25 @@ if test $failure = false; then
   done
 fi
 
+# Format creation check.  Unfortunately we have never got exit codes right.
+install_tl_log=$tltryinst/$yyyy/install-tl.log
+
+if grep -i '^fmtutil: Error' $install_tl_log >/dev/null; then
+  echo >&2
+  echo "$0: seems fmtutil failed, check $install_tl_log." >&2
+  failure=true
+fi
+
+# In all cases, make copies in /tmp for inspection in case of
+# undetected failure.
+cp -f $tlnet_install_log $install_tl_log /tmp
+
 if $failure; then
-  echo
-  echo "$0: Full transcript file: `pwd`/install.log" >&2
-  echo "$0: install-tl complete log file: $tltryinst/$yyyy/install-tl.log" >&2
-  echo "$0: Remember to clean up the trial dir, please." >&2
+  echo >&2
+  echo "$0: Our transcript file: $tlnet_install_log" >&2
+  echo "$0: install-tl log file: $install_tl_log" >&2
+  echo "$0: Copies of both are in /tmp." >&2
+  echo "$0: Please rm -rf the trial dir." >&2
   exit 1
 fi
 
